-- User Table
create table
  public."User" (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    username text not null,
    password text not null,
    first_name text not null default ''::text,
    last_name text not null default ''::text,
    constraint User_pkey primary key (id),
    constraint User_username_key unique (username)
  ) tablespace pg_default;

-- Posts Table
create table
  public."Posts" (
    post_id bigint generated by default as identity,
    date timestamp with time zone not null default now(),
    username bigint null,
    contents text null,
    likes integer null,
    dislikes integer null,
    constraint Post_pkey primary key (post_id)
  ) tablespace pg_default;

-- Followers Table
create table
  public."Followers" (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    user_id bigint null,
    follower text null,
    constraint Followers_pkey primary key (id)
  ) tablespace pg_default;

-- Comments Table
create table
  public."Comment" (
    id bigint generated by default as identity,
    date timestamp with time zone not null default now(),
    user_id bigint null,
    post_id bigint null,
    content text null,
    constraint Comment_pkey primary key (id),
    constraint Comment_post_id_fkey foreign key (post_id) references "Posts" (post_id)
  ) tablespace pg_default;

-- Pre-Populated Data
INSERT INTO user 
(username, password, first_name, last_name)
VALUES 
('jesus', 'password', 'jesus', 'avalos');
